"""Utilities for handling A2UI components within the ADK agent.

This module provides helper functions to wrap A2UI JSON messages for the ADK web client,
extract A2UI JSON from model outputs, and handle common issues like echoed blobs
and truncated JSON.
"""

import json
import logging
import re

from google.adk.agents.callback_context import CallbackContext
from google.adk.models.llm_request import LlmRequest
from google.adk.models.llm_response import LlmResponse
from google.genai import types

logger = logging.getLogger(__name__)

_A2UI_BLOB_MARKER = b"<a2a_datapart_json>"
_A2UI_BLOB_MARKER_STR = "<a2a_datapart_json>"


def _wrap_a2ui_part(a2ui_message: dict) -> types.Part:
    """Wraps a single A2UI message for rendering in the ADK web client.

    Args:
        a2ui_message: The A2UI JSON message (as a dictionary) to wrap.

    Returns:
        A `google.genai.types.Part` containing the wrapped A2UI blob.
    """
    datapart_json = json.dumps(
        {
            "kind": "data",
            "metadata": {"mimeType": "application/json+a2ui"},
            "data": a2ui_message,
        }
    )
    blob_data = (
        _A2UI_BLOB_MARKER + datapart_json.encode("utf-8") + b"</a2a_datapart_json>"
    )
    return types.Part(
        inline_data=types.Blob(
            data=blob_data,
            mime_type="text/plain",
        )
    )


def _strip_a2a_wrappers(text: str) -> str:
    """Removes any <a2a_datapart_json>...</a2a_datapart_json> blocks from text.

    These are echoed blobs from conversation history that the model regurgitates.
    We strip them so the raw-JSON fallback in _extract_a2ui_json doesn't
    accidentally pick them up instead of the actual A2UI JSON.

    Args:
        text: The input text containing potential A2UI wrappers.

    Returns:
        The text with all A2UI wrappers removed.
    """
    return re.sub(
        r"<a2a_datapart_json>.*?</a2a_datapart_json>", "", text, flags=re.DOTALL
    )


def _extract_a2ui_json(text: str) -> str | None:
    """Extracts A2UI JSON from model output.

    Handles (in priority order):
    1. <a2ui-json>...</a2ui-json> tags (generated by A2uiSchemaManager prompt).
    2. Markdown-fenced JSON blocks (```json ... ```).
    3. Raw JSON arrays/objects (after stripping any <a2a_datapart_json> wrappers).

    Args:
        text: The raw text from the model output.

    Returns:
        The extracted JSON string, or None if no valid A2UI JSON is found.
    """
    # 1. Try <a2ui-json> tags first (what the schema manager prompt produces)
    tag_match = re.search(r"<a2ui-json>(.*?)</a2ui-json>", text, re.DOTALL)
    if tag_match:
        return tag_match.group(1).strip()

    # 2. Try markdown fences
    fence_match = re.search(r"```(?:json)?\s*([\[\{].*?)\s*```", text, re.DOTALL)
    if fence_match:
        return fence_match.group(1).strip()

    # 3. Strip any echoed <a2a_datapart_json> wrappers before raw JSON extraction
    #    so we don't accidentally pick up the wrapper's '{' as the JSON start.
    clean_text = _strip_a2a_wrappers(text).strip()

    # 4. Fall back to raw JSON: find the first [ or { to the last ] or }
    json_start = -1
    for i, ch in enumerate(clean_text):
        if ch in ("[", "{"):
            json_start = i
            break

    json_end = -1
    for i, ch in enumerate(reversed(clean_text)):
        if ch in ("]", "}"):
            json_end = len(clean_text) - i
            break

    if json_start != -1 and json_end != -1 and json_start < json_end:
        return clean_text[json_start:json_end]

    return None


def _sanitize_json(text: str) -> str:
    """Replaces common model-generated JSON corruption before parsing.

    Models sometimes emit smart/curly double quotes inside JSON
    string values. Replacing them with bare " would terminate the JSON string
    early; we escape them as \\" instead.

    Args:
        text: The JSON string to sanitize.

    Returns:
        The sanitized JSON string.
    """
    # Curly double quotes -> escaped straight double quotes (safe inside strings)
    text = text.replace("\u201c", '\\"').replace("\u201d", '\\"')
    # Curly single quotes -> straight apostrophes (safe, they're just Unicode content)
    text = text.replace("\u2018", "'").replace("\u2019", "'")
    return text


def _parse_json_greedy(text: str) -> list:
    """Parses all top-level JSON values from text using raw_decode.

    Unlike json.loads(), this handles:
    - A single JSON array:  [{...}, {...}]
    - Concatenated objects: {...} {...} (no comma or array wrapper)
    - Trailing non-JSON content (stops gracefully instead of raising)

    Args:
        text: The text to parse.

    Returns:
        A flat list of all parsed JSON values.

    Raises:
        json.JSONDecodeError: If no valid JSON was found at all.
    """
    decoder = json.JSONDecoder()
    results = []
    idx = 0
    text = text.strip()
    while idx < len(text):
        # Skip whitespace between objects
        while idx < len(text) and text[idx] in " \t\n\r":
            idx += 1
        if idx >= len(text):
            break
        # Stop if next char is not the start of a JSON value
        if text[idx] not in '[{"tfn0123456789-':
            break
        try:
            obj, end = decoder.raw_decode(text, idx)
        except json.JSONDecodeError as e:
            logger.warning(
                f"_parse_json_greedy: raw_decode failed at idx={idx}: {e}; "
                f"context around pos {e.pos}: {text[max(0, e.pos - 30) : e.pos + 30]!r}"
            )
            break  # Can't parse here, stop gracefully
        if isinstance(obj, list):
            results.extend(obj)
        else:
            results.append(obj)
        idx = end
    if not results:
        raise json.JSONDecodeError("No valid JSON found", text, 0)
    return results


def _repair_json(text: str) -> list | None:
    """Tries to repair truncated JSON by adding missing closing brackets/braces.

    Handles the case where the model generates JSON that's cut off before
    all array/object brackets are properly closed.

    Args:
        text: The potentially truncated JSON string.

    Returns:
        A list of repaired JSON objects if successful, otherwise None.
    """
    opens = {"{": "}", "[": "]"}
    closes = {"}", "]"}
    stack = []
    in_string = False
    escape_next = False

    for ch in text:
        if escape_next:
            escape_next = False
            continue
        if ch == "\\" and in_string:
            escape_next = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch in opens:
            stack.append(opens[ch])
        elif ch in closes:
            if stack and stack[-1] == ch:
                stack.pop()

    if not stack:
        # Already structurally balanced — try json.loads directly.
        try:
            result = json.loads(text)
            return result if isinstance(result, list) else [result]
        except json.JSONDecodeError:
            return None

    # If truncation happened inside a string value (e.g. a long URL),
    # close the string first before adding structural brackets.
    suffix = '"' if in_string else ""
    repaired = text + suffix + "".join(reversed(stack))
    try:
        result = json.loads(repaired)
        return result if isinstance(result, list) else [result]
    except json.JSONDecodeError:
        return None


def before_model_callback(
    callback_context: CallbackContext,
    llm_request: LlmRequest,
) -> LlmResponse | None:
    """Strips A2UI blobs from history so the model doesn't regurgitate them.

    Replaces A2UI inline-data blobs in conversation history with a
    '[A2UI component rendered]' placeholder.

    Args:
        callback_context: The context for the callback.
        llm_request: The outgoing LLM request.

    Returns:
        None to continue with the (now-clean) request.
    """
    if not llm_request.contents:
        return None

    for content in llm_request.contents:
        if not content.parts:
            continue
        clean_parts = [
            types.Part(text="[A2UI component rendered]")
            if (
                p.inline_data
                and p.inline_data.mime_type == "text/plain"
                and _A2UI_BLOB_MARKER in (p.inline_data.data or b"")
            )
            else p
            for p in content.parts
        ]
        content.parts[:] = clean_parts

    return None  # Continue with the (now-clean) request


def a2ui_callback(
    callback_context: CallbackContext,
    llm_response: LlmResponse,
) -> LlmResponse | None:
    """Converts A2UI JSON in text output to rendered components.

    This callback scans the model response for A2UI JSON blocks, extracts them,
    and wraps them as inline-data blobs that the ADK web client can render.

    Args:
        callback_context: The context for the callback.
        llm_response: The incoming LLM response.

    Returns:
        A new LlmResponse with A2UI blobs if any were found, otherwise None.
    """
    if not llm_response.content or not llm_response.content.parts:
        return None

    a2ui_keys = {
        "beginRendering", "surfaceUpdate", "dataModelUpdate", "deleteSurface",
        # Also detect bare component payloads the model may emit directly
        "surfaceId", "components",
    }

    new_parts = []
    found_a2ui = False
    num_parts = len(llm_response.content.parts)
    logger.info(f"a2ui_callback: called with {num_parts} part(s)")

    for part_idx, part in enumerate(llm_response.content.parts):
        if not part.text:
            logger.info(
                f"a2ui_callback: part {part_idx} has no text (inline_data={bool(part.inline_data)})"
            )
            new_parts.append(part)
            continue

        text = part.text.strip()

        # Skip parts that are ONLY echoed <a2a_datapart_json> wrappers
        if _A2UI_BLOB_MARKER_STR in text:
            stripped = _strip_a2a_wrappers(text).strip()
            if not stripped:
                # Purely an echoed blob — discard entirely
                logger.info("a2ui_callback: discarding echoed <a2a_datapart_json> part")
                continue
            # Has both wrapper and new content; work on stripped version
            text = stripped

        if not any(k in text for k in a2ui_keys):
            logger.info(
                f"a2ui_callback: part {part_idx} has no A2UI keys, passing through"
            )
            new_parts.append(types.Part(text=text))
            continue

        logger.info(
            f"a2ui_callback: part {part_idx} has A2UI keys, len={len(text)}, first_50={text[:50]!r}"
        )
        json_text = _extract_a2ui_json(text)
        if json_text is None:
            logger.warning(
                f"a2ui_callback: part {part_idx} - A2UI keys found but JSON extraction failed"
            )
            logger.warning(f"  full text: {text!r}")
            new_parts.append(types.Part(text=text))
            continue
        logger.info(
            f"a2ui_callback: extracted json_text len={len(json_text)}, last_20={json_text[-20:]!r}"
        )

        # Sanitize smart/curly quotes before parsing
        json_text = _sanitize_json(json_text)

        try:
            parsed = _parse_json_greedy(json_text)
        except json.JSONDecodeError as e:
            logger.warning(f"a2ui_callback: JSON parse failed, trying repair: {e}")
            logger.warning(f"  json_text (first 300): {json_text[:300]!r}")
            logger.warning(f"  json_text (last 100): {json_text[-100:]!r}")
            parsed = _repair_json(json_text)
            if parsed is None:
                logger.warning(
                    "a2ui_callback: JSON repair also failed, passing through"
                )
                new_parts.append(types.Part(text=text))
                continue
            logger.info(
                f"a2ui_callback: JSON repair succeeded, got {len(parsed)} objects"
            )

        if not isinstance(parsed, list):
            parsed = [parsed]

        # ── Normalize: wrap bare {surfaceId, components} into surfaceUpdate ──
        wrapped_keys = {"beginRendering", "surfaceUpdate", "dataModelUpdate", "deleteSurface"}
        normalized: list[dict] = []
        for m in parsed:
            if not isinstance(m, dict):
                continue
            if any(k in m for k in wrapped_keys):
                # Already in proper envelope format
                normalized.append(m)
            elif "surfaceId" in m and "components" in m:
                # Bare component payload — wrap it
                surface_id = m["surfaceId"]
                components = m["components"]
                logger.info(
                    f"a2ui_callback: auto-wrapping bare payload for surface {surface_id}"
                )
                # Inject beginRendering + surfaceUpdate pair
                if components and isinstance(components, list) and isinstance(components[0], dict):
                    root_id = components[0].get("id", surface_id)
                    normalized.append(
                        {"beginRendering": {"surfaceId": surface_id, "root": root_id}}
                    )
                normalized.append(
                    {"surfaceUpdate": {"surfaceId": surface_id, "components": components}}
                )
            elif "surfaceId" in m:
                # Other bare payloads with surfaceId (e.g. data model updates)
                normalized.append(m)

        msgs = normalized
        if not msgs:
            new_parts.append(types.Part(text=text))
            continue

        # Auto-inject beginRendering if missing (for standard surfaceUpdate msgs)
        has_begin = any("beginRendering" in m for m in msgs)
        if not has_begin:
            for m in msgs:
                if "surfaceUpdate" in m:
                    surface_id = m["surfaceUpdate"].get("surfaceId")
                    components = m["surfaceUpdate"].get("components", [])
                    if surface_id and components:
                        logger.info(
                            f"a2ui_callback: auto-injecting beginRendering for {surface_id}"
                        )
                        msgs.insert(
                            0,
                            {
                                "beginRendering": {
                                    "surfaceId": surface_id,
                                    "root": components[0]["id"],
                                }
                            },
                        )
                    break

        logger.info(
            f"a2ui_callback: creating {len(msgs)} A2UI blob(s) for part {part_idx}"
        )
        new_parts.extend([_wrap_a2ui_part(m) for m in msgs])
        found_a2ui = True

    if not found_a2ui:
        return None

    return LlmResponse(
        content=types.Content(role="model", parts=new_parts),
        custom_metadata={"a2a:response": "true"},
    )
